### ISSUE TITLE
Add Contributing file

### ISSUE THREAD

**Issue by Dun-sin** [openprivacytech/openprivacytech.org#12]
Adding the contributing file is useful for new contributors, so they know what to do in this project

Here's a reference link: [Contributing.md](https://mozillascience.github.io/working-open-workshop/contributing/)

**Comment by souravcipher** [comment]
I have assigned you to this issue @Dun-sin !

**Comment by Dun-sin** [comment]
Got it, thanks, will work on this as soon as possible
