### ISSUE TITLE
add templates

### ISSUE THREAD

**Issue by Dun-sin** [openprivacytech/openprivacytech.org#13]
I saw this project is open to contributions, and it doesn't have Pull request and issue templates, it makes it easier for you to maintain your projects.

I can work on this is you want

Here are links for reference: 
[Pull Request Template](https://learn.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
[Pull Request and Issue Template](https://bakingclouds.com/multiple-template-choices/)

**Comment by souravcipher** [comment]
This will be awesome, @Dun-sin!

**Comment by souravcipher** [comment]
Go for it. 🚀

**Comment by souravcipher** [comment]
Just mention this issue in your PR.

closing.
