### ISSUE TITLE
Add "Page under construction flag" to all the pages that are under work right now

### ISSUE THREAD

**Issue by crsdvaibhav** [openprivacytech/openprivacytech.org#19]
<img width="960" alt="1" src="https://user-images.githubusercontent.com/95699355/193364209-6a8202f3-11bf-4b39-ab05-b721af5ef6af.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/95699355/193364237-a48c6014-cfb0-492e-83cc-867e520358df.png">

### We can add a flag, that is a bar in the body of every page that tells that it is under construction right now. The empty pages look broken :)

**Comment by crsdvaibhav** [comment]
@souravcipher Can you assign this issue to me?

**Comment by souravcipher** [comment]
This is still under development @crsdvaibhav! 

Closing the issue, you can go ahead and submit a PR.

Just add something like 
`This page is under construction!`
