### ISSUE TITLE
UI Improvement (Homepage)

### ISSUE THREAD

**Issue by RidhamRj** [openprivacytech/openprivacytech.org#29]
Hey there,
I am a HacktoberFest2022 Participant
I would like To work on the homepage UI.
Would like to Change color and add some more functionalities may be like loader

Features-
- [x] Homepage UI improvement 

kindly assign this and make any suggestions to improve the UI

**Comment by RidhamRj** [comment]
@souravcipher kindly suggest and assign for the features

**Comment by souravcipher** [comment]
Hi, I think I'll create a few more issues in the coming days.

For now, closing this one! Thanks.
