### ISSUE TITLE
Create sidebar for Resources

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/openprivacytech.org#3]
The resources page should have a sidebar for Federated Learning, Differential Privacy, etc.

Please check the [Documentation](https://docusaurus.io/docs/sidebar) first and leave a comment here if you're interested in contributing.

**Comment by Swetha-kodam** [comment]
Hello... I'm interested in working on this sidebar

**Comment by souravcipher** [comment]
Hi @Swetha-kodam, sure - we are using [docusaurus](https://docusaurus.io) to build this website. 

Please check out the [documentation](https://docusaurus.io/docs) and feel free to submit a PR. 
Here's an example for the sidebar 
[Getting-Started-Docusaurus.webm](https://user-images.githubusercontent.com/72210541/191338571-3564b1b8-d624-4659-bd21-d0343f3cbb0b.webm)

**Comment by folarindeb** [comment]
Hello... I'm interested in working on this sidebar

**Comment by Swetha-kodam** [comment]
Hello @souravcipher ,so I'm going through the docusaurus and about sidebar 
so can i know first what are the items we need to be aligned in the sidebar and also the sub domain items.

**Comment by souravcipher** [comment]
Yeah - you have to create a sidebar for `Resources` and create categories for each topic like FL, DP, etc.
The structure should be like this.

- Resources
   - Federated Learning
   - Differential Privacy
   - Homomorphic Encryption
   - Secure Multi-Party Computation

**Comment by Swetha-kodam** [comment]
Thanks, I'll check it out.

**Comment by Swetha-kodam** [comment]
hello... @souravcipher 
Actually I've a doubt, I'm trying to build sidebar using html and css. Is that fine?
or as mentioned in docusaurus should we built it in react?
If using html and css, can uh help me out where are those specific files.

**Comment by souravcipher** [comment]
You don't need to write separate HTML/CSS codes to create a sidebar just follow the [sidebar documentation](https://docusaurus.io/docs/sidebar). Sidebar is already there all you have to do is add a directory with the name(resources), add the .md files and add it in the .js file. The structure should be like this - 

either - 
- docs/resources/
  - federated-learning.md
  - differential-privacy.md
  - homomorphic-encryption.md
  - secure-multi-party-computation.md

or 

- /resources/
  - federated-learning.md
  - differential-privacy.md
  - homomorphic-encryption.md
  - secure-multi-party-computation.md


I'd suggest following these steps to understand more
 1. Read the [documentation](https://docusaurus.io/docs/) first.
 2. Install a new project(from [here](https://docusaurus.io/docs/installation)) on your machine and understand how the docusaurus works.
 3. Check out the project structure, sidebar js, plugins, config files, etc. 
 4. Once you understand the whole thing come back to this project and implement the sidebar with the structure I have mentioned above. 
 5. You can also [join the docusaurus discord ](https://discordapp.com/invite/docusaurus)and ask for help. 
 
If you complete this issue you will be comfortable working with other static generators like Jekyll, Hugo, etc.

**Comment by Swetha-kodam** [comment]
Thanks a lot for making your time  and for a brief explanation. Now I got clear idea. Sure I’ll go through everything as uh mentioned and will complete this issue Sent from Mail for Windows From: Sourav DasSent: 23 September 2022 19:26To: OpenPrivacyTech/openprivacytech.orgCc: Swetha-kodam; AssignSubject: Re: [OpenPrivacyTech/openprivacytech.org] Create sidebar for Resources (Issue #3) You don't need to write separate HTML/CSS codes to create a sidebar just follow the sidebar documentation. Sidebar is already there all you have to do is add a directory with the name(resources) and add the .md files. The structure should be like this -either -docs/resources/ federated-learning.mddifferential-privacy.mdhomomorphic-encryption.mdsecure-multi-party-computation.mdor/resources/ federated-learning.mddifferential-privacy.mdhomomorphic-encryption.mdsecure-multi-party-computation.mdI'd suggest following these steps to understand moreRead the documentation first.Install a new project(from here) on your machine and understand how the docusaurus works.Check out the project structure, sidebar js, plugins, config files, etc.Once you understand the whole thing come back to this project and implement the sidebar with the structure I have mentioned above.You can also join the docusaurus discord and ask for help.If you complete this issue you will be comfortable working with other static generators like Jekyll, Hugo, etc.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by souravcipher** [comment]
Hi @Swetha-kodam, any update on this?

please let me know how I can help!

**Comment by RidhamRj** [comment]
hey is this repo for hacktoberfest2022?

**Comment by RidhamRj** [comment]
@souravcipher

**Comment by souravcipher** [comment]
Hi @RidhamRj, yeah!

We are participating in hacktoberfest.

**Comment by RidhamRj** [comment]
> Hi @RidhamRj, yeah!
> 
> We are participating in hacktoberfest.

All right i will go through the docs first
By this repo i came through quite an interesting feature i didn't knew

**Comment by Preet-Sojitra** [comment]
If this issue still open then I would I to work on this

**Comment by souravcipher** [comment]
Hi @Preet-Sojitra, I think @RidhamRj is working on it.

**Comment by Preet-Sojitra** [comment]
@RidhamRj are you working on this?

**Comment by RidhamRj** [comment]
> @RidhamRj are you working on this?

actually first i am going through the docs
i was trying add sidebar but myself was stuck
so will tell you if there's any update

**Comment by RidhamRj** [comment]
> If this issue still open then I would I to work on this

for me it would take some time 
i will let you know the updates

**Comment by Preet-Sojitra** [comment]
ok no problem 👍

**Comment by Swetha-kodam** [comment]
Hello..Actually I’ve gone through entire documentation of docusaurus and  got some idea. I tried to it create  a pull request but the changes are not showing in my repository.  Sent from Mail for Windows From: Sourav DasSent: 29 September 2022 01:11To: openprivacytech/openprivacytech.orgCc: Swetha-kodam; MentionSubject: Re: [openprivacytech/openprivacytech.org] Create sidebar for Resources (Issue #3) Hi @Swetha-kodam, any update on this?please let me know how I can help!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ziarparvaiz** [comment]
@souravcipher Can you give me sidebar list I will do this I have a experience on docusaurus I did a project on docusaurus If you wouldn't mind I can do this for you.

**Comment by souravcipher** [comment]
Hi @ziarparvaiz! 

Contributions are welcome. I was about to complete it this weekend but go ahead as you already have the experience with docusaurus!

**Comment by ziarparvaiz** [comment]
Thanks share to me sidebar list and assign me this issue to.

**Comment by souravcipher** [comment]
> Yeah - you have to create a sidebar for `Resources` and create categories for each topic like FL, DP, etc.
> The structure should be like this.
> 
> - Resources
>    - Federated Learning
>    - Differential Privacy
>    - Homomorphic Encryption
>    - Secure Multi-Party Computation 

@ziarparvaiz

**Comment by souravcipher** [comment]
> You don't need to write separate HTML/CSS codes to create a sidebar just follow the [sidebar documentation](https://docusaurus.io/docs/sidebar). Sidebar is already there all you have to do is add a directory with the name(resources), add the .md files and add it in the .js file. The structure should be like this - 
> 
> either - 
> - docs/resources/
>   - federated-learning.md
>   - differential-privacy.md
>   - homomorphic-encryption.md
>   - secure-multi-party-computation.md
> 
> or 
> 
> - /resources/
>   - federated-learning.md
>   - differential-privacy.md
>   - homomorphic-encryption.md
>   - secure-multi-party-computation.md
> 
> 
> I'd suggest following these steps to understand more
>  1. Read the [documentation](https://docusaurus.io/docs/) first.
>  2. Install a new project(from [here](https://docusaurus.io/docs/installation)) on your machine and understand how the docusaurus works.
>  3. Check out the project structure, sidebar js, plugins, config files, etc. 
>  4. Once you understand the whole thing come back to this project and implement the sidebar with the structure I have mentioned above. 
>  5. You can also [join the docusaurus discord ](https://discordapp.com/invite/docusaurus)and ask for help. 
>  
> If you complete this issue you will be comfortable working with other static generators like Jekyll, Hugo, etc.

@ziarparvaiz

**Comment by ziarparvaiz** [comment]
😊 @souravcipher  Okay I will do this please assign me this issue. &
Check my docusaurus project if you like any features there tell me

Repo:- https://github.com/Fire-Oceann/BB-TR-Kaynak
Website:- https://bb-tr-kaynak.netlify.app/

The website is Turkish don't pay attention you check the UI Component and tell me.

**Comment by ziarparvaiz** [comment]
@souravcipher If that's okay, I'll send.

![sidebarList](https://user-images.githubusercontent.com/50423368/194390771-af7e87b5-e765-4165-800e-4c4c7e949315.gif)

**Comment by souravcipher** [comment]
The /docs will have different sets of documentation; I want to have them separately for now! 

Could you please make the Resouces a separate sidebar?

the structure should be 
/resources/

- federated-learning.md
- differential-privacy.md
- homomorphic-encryption.md
- secure-multi-party-computation.md

Without the dropdown, each .md file should be separated and when ''Resources'' is clicked it should open the federated-learning.md first.

sorry for the confusion, I think this is better and should work for me! There will be more pages as well.

**Comment by ziarparvaiz** [comment]
> The /docs will have different sets of documentation; I want to have them separately for now!
> 
> Could you please make the Resouces a separate sidebar?
> 
> the structure should be /resources/
> 
>     * federated-learning.md
> 
>     * differential-privacy.md
> 
>     * homomorphic-encryption.md
> 
>     * secure-multi-party-computation.md
> 
> 
> Without the dropdown, each .md file should be separated and when ''Resources'' is clicked it should open the federated-learning.md first.
> 
> sorry for the confusion, I think this is better and should work for me! There will be more pages as well.

I can do that, but there is a URL conflict. You already have a `/resources` page, we need to change it to the filename.
https://www.openprivacytech.org/resources/

**Comment by souravcipher** [comment]
For the current [resource page](https://github.com/openprivacytech/openprivacytech.org/blob/main/src/pages/resources.md) content just move it to the resources folder, just like the docs folder! I'll move the contents to different pages!

**Comment by souravcipher** [comment]
yeah

> > The /docs will have different sets of documentation; I want to have them separately for now!
> > Could you please make the Resouces a separate sidebar?
> > the structure should be /resources/
> > ```
> > * federated-learning.md
> > 
> > * differential-privacy.md
> > 
> > * homomorphic-encryption.md
> > 
> > * secure-multi-party-computation.md
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Without the dropdown, each .md file should be separated and when ''Resources'' is clicked it should open the federated-learning.md first.
> > sorry for the confusion, I think this is better and should work for me! There will be more pages as well.
> 
> I can do that, but there is a URL conflict. You already have a `/resources` page, we need to change it to the filename. https://www.openprivacytech.org/resources/

I see, this page needs to be removed I guess for the URL conflict or it can be a [category page](https://docusaurus.io/docs/category/getting-started) maybe? what do you suggest?

Both work for me though! You can go ahead and submit a PR. I'll review the PR and leave the comments there!

**Comment by ziarparvaiz** [comment]
I will transfer the file to the content on the resources page (/contents/resources/into.md) and (/src/page/resources.md) delete It

**Comment by ziarparvaiz** [comment]
Ok, I got you, I'll send a PR.

**Comment by Swetha-kodam** [comment]
Hello...
I'll start working on it from now on.
