### ISSUE TITLE
Bug : Mobile responsiveness fixes 🛠

### ISSUE THREAD

**Issue by tamalCodes** [openprivacytech/openprivacytech.org#31]
## Problems i noticed  : 

- The website's landing page has some broken parts specially when opened in mobiles
- The Website's footer has all the elements stacked vertically, which technically wastes alot of space

## Can i fix it ? 

- Yes i can work on it and fix it too
- The UI/UX will be greatly improved if the changes are made
- This can also be a great improvement in Hacktoberfest !

## Homepage buttons

![image](https://user-images.githubusercontent.com/72851613/193393256-b220b7e0-5dc0-48c7-8fdd-e30a79a5b2ca.png)

## Footer looks 

![image](https://user-images.githubusercontent.com/72851613/193393376-5db0fa17-d8d0-4bb2-8bec-b03013eef286.png)

**Comment by souravcipher** [comment]
Hey @IAmTamal, glad you noticed. 

This seems critical - feel free to submit a PR on this.
