### ISSUE TITLE
[DOCS] <Add 'Table of Contents' section in the documentation.>

### ISSUE THREAD

**Issue by bhattabhi013** [openprivacytech/openprivacytech.org#35]
### Description

Add 'Table of Contents' section in `README.md`.

**Comment by KugelPfusch** [comment]
I'll do this

**Comment by bhattabhi013** [comment]
Hi @KugelPfusch ,
I'm working on it.
Currently, waiting for the project admin to assign me so that I can raise a PR.

**Comment by souravcipher** [comment]
It's not required at this time! Thanks.
