### ISSUE TITLE
Change the url color

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/openprivacytech.org#4]
URL colors are the same as text  color -> change the color to any different color.

Also, make sure that in dark mode and light mode the color is highlighted!

**Comment by Manoharvuradi** [comment]
I would like to work on this issue!

**Comment by souravcipher** [comment]
Hi @Manoharvuradi go for it.

**Comment by souravcipher** [comment]
Assigning you to this issue.

**Comment by souravcipher** [comment]
Hi @Manoharvuradi, any update on this?

**Comment by Manoharvuradi** [comment]
Hello @souravcipher 
Right now im busy with my college works.you can assign this issue to someone.
Sorry for the delay.

**Comment by souravcipher** [comment]
this is issue is associated with #5

**Comment by zghp** [comment]
Hi, anyone working on this issue? If no then I'd like to work on it

**Comment by souravcipher** [comment]
You are welcome to contribute @zghp !

**Comment by KanishkDadhich** [comment]
Hey @souravcipher . I would like to work on this issue!

**Comment by heggrik** [comment]
@souravcipher Which URLs are we discussing here? the navbar-links or just general links?

**Comment by souravcipher** [comment]
Hi @heggrik, not navbar - it's for the general links in pages.

e.g. if you visit [coc](openprivacytech.org/code-of-conduct) or [resources](https://www.openprivacytech.org/resources) the links have similar color. 

so it should be highlighted for all the pages. except for the footer/navbar.

**Comment by heggrik** [comment]
@souravcipher 

Got it, tough i'm not entirely sure what you mean by "Also, make sure that in dark mode and light mode the color is highlighted!"

Also, be aware that changing URL-colors makes the titles in [blog](https://www.openprivacytech.org/blog) the same color.

**Comment by souravcipher** [comment]
I think the default color on docusaurus should work. 
> "Also, make sure that in dark mode and light mode the color is highlighted!"
here's an example. 
[url color in light:dark mode.webm](https://user-images.githubusercontent.com/72210541/193367663-6b5a614b-0489-4f02-a8ae-4635c234e4ac.webm)

You may submit a PR.
