### ISSUE TITLE
Website UI design [discussions]

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/openprivacytech.org#47]
### Description

A cool gradient background, animation, or interactive cards.

**Comment by ziarparvaiz** [comment]
can u explain It little bit more do u have any pic of the ui interactive cards did u can share.

**Comment by souravcipher** [comment]
Nope, I don't have any UI design at this moment but exploring good designs which are built w/ or w/o docusaurus. I'd prefer something like a dark gradient in the background. Looking for some inspiration.

**Comment by ziarparvaiz** [comment]
I can do the interface I will share it then we can discuss on it.

**Comment by souravcipher** [comment]
Sounds great @ziarparvaiz! 

Love to chat.

**Comment by souravcipher** [comment]
Hi @ziarparvaiz, we are working on branding for OpenPrivacyTech. I'm planning to start a web development sprint next year! You may join it if you're interested.

**Comment by ziarparvaiz** [comment]
@souravcipher Of course I would like

**Comment by osamahassani05355881581** [comment]
> ### Description
> 
> A cool gradient background, animation, or interactive cards.
> 
> ### Screenshots
> 
> _No response_
