### ISSUE TITLE
footer link color [need attention]

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/openprivacytech.org#5]
Change the footer link color for light mode, 
It should not change the color if the cursor is on it in light mode.

> The dark mode is fine.

**Comment by yadavsairaj** [comment]
Hey can i work on this issue?

**Comment by souravcipher** [comment]
Hi @yadavsairaj, you need to go through the codebase first and the site generator [docusaurus](https://docusaurus.io/docs).

Contributions are welcome.

**Comment by developerkunal** [comment]
i would like to solve this issue

**Comment by developerkunal** [comment]
#11

**Comment by developerkunal** [comment]
can you assign this me so hacktober fest will know about it
