### ISSUE TITLE
Add announcementBar

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/openprivacytech.org#50]
### Description

Add the announcementBar, 

It should include simple message `This site is under construction, don't forget to star the repo on GitHub`

**Comment by DHRUVKHANDELWAL00** [comment]
hey @souravcipher , please assign me.

**Comment by souravcipher** [comment]
Hi @DHRUVKHANDELWAL00! Are you familiar with Docusaurus?

You are welcome to submit a PR.

**Comment by souravcipher** [comment]
This issue is open for contributions!

**Comment by ziarparvaiz** [comment]
@souravcipher If it's still open u can assign me?

**Comment by souravcipher** [comment]
The website UI will be changed soon and there'll be more contents! 

For now, we just need to mention it that it's under development!
