### ISSUE TITLE
[BUG] Slack invite not working

### ISSUE THREAD

**Issue by Neilblaze** [openprivacytech/openprivacytech.org#52]
### Description

The [slack invite](https://www.openprivacytech.org/#:~:text=JOIN%20THE%20COMMUNITY) (via [communityinviter](https://communityinviter.com/apps/openprivacytech/openprivacytech)) is not working. Tried with multiple (3x) emails, still the same.

**Response** → No slack invite magic link is received.

### Screenshots

![image](https://user-images.githubusercontent.com/48355572/227743972-23ac6ccb-020c-4937-95fc-7e081bb70f71.png)

> Says, `email` is already registered & declines re-requests.

**Comment by souravcipher** [comment]
Thank you, updated the link with our new slack workspace.
