### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/openprivacytech.org#7]
Create an awesome Readme for this repo

- add badges 
- add steps to contribute 
- add npm steps instead of yarn

**Comment by kanishk6103** [comment]
Can I add steps to contribute if that's okay?

**Comment by mehraankush** [comment]
npm for react .

**Comment by fynefav3** [comment]
Is this a react program, Can you explain this so i can contribute

**Comment by kanishk6103** [comment]
> Create an awesome Readme for this repo
> 
> * add badges
> * add steps to contribute
> * add npm instead of yarn

I have added steps to contribute, and sent a PR
