### ISSUE TITLE
Center footer content

### ISSUE THREAD

**Issue by developer-diganta** [openprivacytech/openprivacytech.org#9]
![image](https://user-images.githubusercontent.com/65999534/193352688-8f6b16f4-beac-4baf-a32e-72a686cbcd8b.png)
The footer content could be centered. if this seems like a legit issue, can I work on it?

**Comment by souravcipher** [comment]
Hi @developer-diganta, sure. 

go for it.

**Comment by souravcipher** [comment]
Closing this issue to avoid spam! Feel free to submit a PR
